### ISSUE TITLE
CLI dont work

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/lib-cove-ocds#103] opened 2022-09-30 21:30 UTC
log details

from `pip install libcoveocds`
```
ERROR: libcove 0.27.0 has requirement jsonschema<4,>=3, but you'll have jsonschema 4.16.0 which is incompatible.
```
from `libcoveocds` cli
```
Traceback (most recent call last):
  File "../py/lib-cove-ocds/pypi/.ve/bin/libcoveocds", line 5, in <module>
    from libcoveocds.cli.__main__ import main
  File "../py/lib-cove-ocds/pypi/.ve/lib/python3.8/site-packages/libcoveocds/cli/__main__.py", line 9, in <module>
    import libcoveocds.api
  File "../py/lib-cove-ocds/pypi/.ve/lib/python3.8/site-packages/libcoveocds/api.py", line 6, in <module>
    from libcove.lib.common import get_spreadsheet_meta_data
  File "../py/lib-cove-ocds/pypi/.ve/lib/python3.8/site-packages/libcove/lib/common.py", line 21, in <module>
    from jsonschema._utils import (
ImportError: cannot import name 'types_msg' from 'jsonschema._utils' (...py/lib-cove-ocds/pypi/.ve/lib/python3.8/site-packages/jsonschema/_utils.py)
```
Seems a jsonschema update, we can solve it if we use `jsonschema==3.2.0`

cc @jpmckinney

**Comment by Ravf95** [comment] 2022-10-01 00:18
DRT fails with the example
https://standard.open-contracting.org/review/data/b7bec8fb-eae2-40bb-9335-77328c1e5dd6
![image](https://user-images.githubusercontent.com/16477965/193374427-4b3027a9-cb87-4fdb-819c-9d73b63c8f3d.png)

**Comment by jpmckinney** [comment] 2022-10-01 03:33
What version of `pip` are you using? Only very old versions of pip have trouble like the above error.

Please upgrade pip and re-open if you can reproduce the error in a fresh virtual environment.

**Comment by Ravf95** [comment] 2022-10-01 17:35
I use pip 22.2.2, I think the problem is an update of jsonschema lib (see [this change](https://github.com/python-jsonschema/jsonschema/commit/00031cb043763842266877923552e40f0c8f36b5) from [v4.16.0](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.16.0))

**Comment by jpmckinney** [comment] 2022-10-03 14:51
Can you provide all the steps to reproduce the issue, from a fresh virtual environment?

It should be impossible to install jsonschema>=4, since libcove specifies "jsonschema>=3,<4".

**Comment by Ravf95** [comment] 2022-11-01 12:58
The problem is that lib-code-ocds overrides jsonschema version required for libcove (see [libcove requires](https://github.com/OpenDataServices/lib-cove/blob/42f91b01bd37a74b52ab5a34699369070d0e62ef/setup.py#L14) and [lib-code-ocds requires](https://github.com/open-contracting/lib-cove-ocds/blob/8a1b2b33bae0a001b429ae4a7b7e7a077cc3d4c9/setup.py#L22))

**Comment by jpmckinney** [comment] 2022-11-01 15:56
@Ravf95 I still need exact, precise instructions on how to reproduce from a fresh virtual environment, as I originally asked.

There is no overriding there. lib-cove-ocds sets no version, so pip is able to determine a version that works for both.

**Comment by jpmckinney** [comment] 2022-11-01 20:57
As you can see, I can't reproduce the error...

https://user-images.githubusercontent.com/26463/199339419-4be7eccc-21e8-49f6-b2e1-f3a611403c6f.mp4

**Comment by jpmckinney** [comment] 2022-11-01 21:02
Anyway, closing as there is no bug to fix. Please follow-up in Slack for troubleshooting. You will need to provide a full list of commands you ran, including creating a fresh virtual environment.

**Closed as completed by jpmckinney** 2022-11-01 21:02 UTC
